### ISSUE TITLE
Set up travis CI and unit tests

### ISSUE THREAD

**Issue by JonasProgrammer** [quicknir/wise_enum#16]
> @JonasProgrammer If you want to help with travis, that would be big! I can open a separate issue for that (or you can). Re dependencies for unit test, I'm definitely fine with cmake, conan is also fine as long as it can easily be changed if necessary. I would like to use boost unit if possible, as I'm trying to get this into boost (it will remain available as a standalone library as well and will not depend on anything else in boost), not sure what framework you used.

I'll try and paste a travis.yml together quickly.

Regarding the test framework, I've used Catch2 (CppCon 2018 talk got me hooked). I can rewrite the assertions if you want though.

As for conan, I did use the quick&diry cmake generator, but I'll switch to `cmake_paths`, which essentially just hints `find_package` to it's installed packages.

**Comment by quicknir** [comment]
Let's start out using your tests as is from Catch2; I don't want to put any onus on you to rewrite things since you're already contributing so much. Catch2 is also a lighter dependency than boost, and rewriting the tests in boost if/when it is accepted into boost would be pretty trivial anyway. Let me know if there's anything else you need from me, I'm new to all 3 of travis, CMake (I know, I know...) and Catch2 so happy to go along with your suggestions.

**Comment by JonasProgrammer** [comment]
I'm working on it and my fork as a feature branch, that actually builds. I'd like to test with more than one compiler version, however, and some of them are still failing (probably because `xenial` provides an old libstdc++ by default).

I'll have a look at it tomorrow, but for now, progress is being made.
