### ISSUE TITLE
Put big WARNING Sign on the main page: Won't work with Visual Studio!

### ISSUE THREAD

**Issue by huberp** [quicknir/wise_enum#41]
I was looking for a enum which gives me little more capabilities like the to_string function.
I found wise_enum. The main page (readme.md) looked promising. 

I took the effort to check it out in my programm.
First I stumled over the __cpluplus thing, then I had to adjust compiler switches, then I stumbled over the 127 macro arguments thing. And after all the hazzle I looked into the Issues and they were all already there.

Please: It does not work in VisualStudio. You got feedback about it. Please place a big red WARNING note that on the main page.
Please spare other people with VisualStudio the effort to try to use it. Sorry, I'm really a bit pissed...

**Comment by peter-moran** [comment]
Could you explain more why this does not work in Visual Studio? Whats the primary problem?

**Comment by quicknir** [comment]
@peter-moran I'm actually not completely sure, at first it seemed like macro limits, so I tried to lower the default number of enumerator cases to help MSVC with that, now it's still not working. The thing is that I don't have a windows dev environment, or MSVC setup, and frankly that's not time I want to put in at the moment. It should be very straightforward for someone who uses MSVC to understand what the problem is.

Nobody has pointed out any issue where my code is not compliant, and I have not used any gcc extensions, so given MSVC is fairly notorious for having a poor preprocessor implementation, I'd suspect the issue is somewhere there. I'm more than happy to help, including detailed explanations, anyone who wants to get this working on MSVC. Let's move that discussion to https://github.com/quicknir/wise_enum/issues/31.

**Comment by quicknir** [comment]
@huberp your comment is pretty obnoxious, think you're missing the part where you think I owe you something. There's literally a CI on the front page for this that shows "failing", if you'd clicked it you would have seen immediately on what compilers this currently passes and fails. Not to mention skimming existing issues. I don't deliberately exclude MSVC from support; I've even made some changes to try to help, there may be a bug in my code or a bug in the MSVC preproprecessor, but either way, that's how software is, it has bugs. Try to keep your comments here constructive in the future, thanks.
