### ISSUE TITLE
Feature: Check if a given value equals one of the enums

### ISSUE THREAD

**Issue by peter-moran** [quicknir/wise_enum#43]
I would like check if a value I have is equivalent to one of my enums.

For example, assume a function `contains`, I would expect it to behave as:
```cpp
WISE_ENUM(Color, (GREEN, 2), RED);

static_assert(wise_enum::contains<Color>(1) == false);
static_assert(wise_enum::contains<Color>(2) == true);
static_assert(wise_enum::contains<Color>(3) == true);
```

**Comment by quicknir** [comment]
@peter-moran That's pretty easy to write yourself. You can use wise enum to loop over the entries and check, and if you want write a small helper function to encapsulate it. But it's not something I'm likely to merge in. Generally things that are both easy to implement and can easily be implemented "outside" the repo aren't likely candidates; everyone will have their own preferred API/approach for these things and it's pretty low value. The main goal of the repo is to do the "hard" stuff of emulating reflection so users don't have to.

**Comment by peter-moran** [comment]
That is a good point, but that would incur a linear search when an auto generated switch statement would be O(1). 

Is the string conversion handled as a switch statement or a linear search?

**Comment by quicknir** [comment]
Enum to string is handled as a switch case. String to enum is handled as linear search. The enum to string switch case is disabled if two enumerators have the same value (because it's ambiguous).

An auto generated switch case isn't necessarily going to be more efficient, it really depends. Linear search will be pretty good for small enums, if you want it to be fast the best of course is to ensure contiguous values and just do the two comparisons. Beyond that, if your enum is truly large with values all over the place then a hash table is probably your best bet.

This feature could probably be implemented efficiently via my switch case "lift" notion.

**Comment by peter-moran** [comment]
Thanks, I’ll just go with using the linear search then. Interesting idea on the switch case lifts.  Thanks for a great library!
